fix running issues
sryza/aas pull request #142
Opened 2021-04-22 15:14 UTC by chansonzhang

1.  modify hacky replacement to get parsing to work with the newest wikidump
2. update the scala.minor.version and spark.version
3. add core-site.xml to resource directory to make the code to work on local machine
4. format the code in PyCharm

2021-04-22 16:08 UTC, srowen reviewed
I agree with a few of these changes, but most I'd revert

2021-04-22 16:08 UTC, srowen commented on ch06-lsa/src/main/scala/com/cloudera/datascience/lsa/AssembleDocumentTermMatrix.scala
> +    val first=kvs.take(100)
I think these two take statements aren't necessary? I don't mind the show() but might be noisy

2021-04-22 16:08 UTC, srowen commented on ch06-lsa/src/main/scala/com/cloudera/datascience/lsa/RunLSA.scala
> +      .config("spark.master", "local")
The code was meant to run on an existing cluster, but, yeah this is fine. Really, people would probably be pasting the code below into a shell to follow along interactively, rather than run these as is, anyway.

2021-04-22 16:08 UTC, srowen commented on ch06-lsa/src/main/scala/com/cloudera/datascience/lsa/RunLSA.scala
> +    val svd = mat.computeSVD(k, computeU = true)
I wouldn't make these trivial changes.

2021-04-22 16:08 UTC, srowen commented on ch06-lsa/src/main/scala/com/cloudera/datascience/lsa/RunLSA.scala
> +      topTerms += sorted.take(numTerms).map { case (score, id) => (termIds(id), score) }
I wouldn't make the whitespace changes either, though, this one I agree with

2021-04-22 16:08 UTC, srowen commented on pom.xml
> +    <scala.minor.version>2.12</scala.minor.version>
No, we want to test against 2.11 too, still. There are profiles for 2.12 below

2021-04-22 16:08 UTC, srowen commented on pom.xml
> +              <arg>-nobootcp</arg>
Why this?

2021-04-24 04:08 UTC, chansonzhang commented on ch06-lsa/src/main/scala/com/cloudera/datascience/lsa/AssembleDocumentTermMatrix.scala
> +    val first=kvs.take(100)
ok, I removed this

2021-04-24 04:14 UTC, chansonzhang commented on ch06-lsa/src/main/scala/com/cloudera/datascience/lsa/RunLSA.scala
> +    val svd = mat.computeSVD(k, computeU = true)
I didn‘t do it on purpose, It's just a PyCharm shortcut sugar.

2021-04-24 04:16 UTC, chansonzhang commented on pom.xml
> +    <scala.minor.version>2.12</scala.minor.version>
Sorry for not noticed the profiles before,  I removed the version update.

2021-04-24 04:16 UTC, chansonzhang commented on pom.xml
> +    <scala.minor.version>2.12</scala.minor.version>
Sorry for not noticed the profiles before,  I removed the version update.

2021-04-24 04:22 UTC, chansonzhang commented on pom.xml
> +              <arg>-nobootcp</arg>
When I run `mvn package` under `ch06-lsa/` there is an error `[ERROR] error: java.lang.NoClassDefFoundError: javax/tools/ToolProvider`, I just add `<arg>-nobootcp</arg> ` as google search result suggested. However, I haven't made it clear, so I removed this in this pull requst also.

2021-04-24 13:08 UTC, srowen requested changes

2021-04-24 13:08 UTC, srowen commented on ch06-lsa/src/main/scala/com/cloudera/datascience/lsa/AssembleDocumentTermMatrix.scala
> +      page.getTitle.contains("(disambiguation)")) {
These unindents are wrong

2021-04-24 13:08 UTC, srowen commented on ch06-lsa/src/main/scala/com/cloudera/datascience/lsa/RunLSA.scala
> +    val svd = mat.computeSVD(k, computeU = true)
OK, but please revert them

2021-04-25 14:12 UTC, merged